/*
 * Speedometer.h
 *
 * Created: 4/9/2018 2:57:48 PM
 *  Author: Developer
 */ 


#ifndef SPEEDOMETER_H_
#define SPEEDOMETER_H_

#include "main.h"

#define SPEEDOMETER_HALL_SWITCH_DDR	DDRD
#define SPEEDOMETER_HALL_SWITCH_PORT PORTD
#define SPEEDOMETER_HALL_SWITCH_PINS PIND
#define SPEEDOMETER_HALL_SWITCH_PIN 2

#define SPEEDOMETER_TIMER_PRESCALER 256
#define SPEEDOMETER_MAX_DELAY 5
#define SPEEDOMETER_TIMER_OCR_VVALUE 1																						//	Determine period and frequency of the timer
#define SPEEDOMETER_RESOLUTION_TIME_US (SPEEDOMETER_TIMER_PRESCALER * SPEEDOMETER_TIMER_OCR_VVALUE)
#define SPEEDOMETER_MAX_TIMER_COUNTER_VALUE (((F_CPU / SPEEDOMETER_TIMER_PRESCALER) / SPEEDOMETER_TIMER_OCR_VVALUE) * SPEEDOMETER_MAX_DELAY)

#define SPEEDOMETER_GENERAL_SAMPLE_TIME 5

// 
// enum SPEEDOMETER_MODES {SPEEDOMETER_SPEED_MEASUREMENT_MODE, SPEEDOMETER_SCREEN_MODE, SPEEDOMETER_WHEEL_LENGTH_SETING_MODE, SPEEDOMETER_LAST_MODE};


void Speedometer_Init (void);
void Speedometer_Settings (void);

void Speedometer_LCD_Nokia_Main (void);

#endif /* SPEEDOMETER_H_ */